In [12]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
## Define the vocabulary size
voc_size = 10000

In [15]:
## One-Hot representaion
one_hot_repre = [one_hot(words,voc_size)for words in sent]
one_hot_repre

[[5881, 8779, 7446, 6579],
 [5881, 8779, 7446, 5310],
 [5881, 6196, 7446, 5748],
 [4934, 5181, 8301, 2702, 8748],
 [4934, 5181, 8301, 2702, 1044],
 [9838, 5881, 6918, 7446, 2142],
 [4870, 4764, 6711, 2702]]

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 

In [17]:
sent_legnth = 8
embedded_docs = pad_sequences(one_hot_repre,padding='pre',maxlen=sent_legnth)
print(embedded_docs)

[[   0    0    0    0 5881 8779 7446 6579]
 [   0    0    0    0 5881 8779 7446 5310]
 [   0    0    0    0 5881 6196 7446 5748]
 [   0    0    0 4934 5181 8301 2702 8748]
 [   0    0    0 4934 5181 8301 2702 1044]
 [   0    0    0 9838 5881 6918 7446 2142]
 [   0    0    0    0 4870 4764 6711 2702]]


In [18]:
## Feautre Represention 
dim = 10

In [19]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length =sent_legnth))
model.compile('adam','mse')

f:\Tejas Project\RNN Project\venv1\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step


array([[[-1.73459761e-02, -9.43429396e-03,  2.19339021e-02,
          3.91117446e-02, -1.98607445e-02, -1.90319866e-03,
         -3.76600400e-02, -7.35104084e-03, -3.52794304e-02,
          1.73538923e-03],
        [-1.73459761e-02, -9.43429396e-03,  2.19339021e-02,
          3.91117446e-02, -1.98607445e-02, -1.90319866e-03,
         -3.76600400e-02, -7.35104084e-03, -3.52794304e-02,
          1.73538923e-03],
        [-1.73459761e-02, -9.43429396e-03,  2.19339021e-02,
          3.91117446e-02, -1.98607445e-02, -1.90319866e-03,
         -3.76600400e-02, -7.35104084e-03, -3.52794304e-02,
          1.73538923e-03],
        [-1.73459761e-02, -9.43429396e-03,  2.19339021e-02,
          3.91117446e-02, -1.98607445e-02, -1.90319866e-03,
         -3.76600400e-02, -7.35104084e-03, -3.52794304e-02,
          1.73538923e-03],
        [ 1.98811293e-03,  1.24375932e-02,  1.51026249e-03,
         -3.83798108e-02, -3.57299075e-02,  9.06098634e-04,
         -1.00069121e-03,  4.44793589e-02,  4.553927

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 5881, 8779, 7446, 6579], dtype=int32)